exports.chats = [
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'},
  {user: 'Ken', text: 'Hello'},
  {user: 'Foo', text: 'Bar baz'},
  {user: 'Test', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus aspernatur, blanditiis laboriosam, animi necessitatibus sapiente.'}
];